#!/usr/bin/env python3
"""Generates scripts/generated/native_build_info.gd for one native (APK) build.

NATIVE IDENTITY ONLY: native versionName (read from the export preset, its authority),
Android build (versionCode), flavour, the source SHA and CI run that produced the APK.
The product version is NOT written here; it is read at runtime from GameVersion.

Usage: write_native_build_info.py <preset name> <flavor> <android build> <sha> <run id> [run url]
"""
import configparser, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def preset_option(preset_name, key):
    cp = configparser.RawConfigParser(strict=False)
    cp.read(ROOT / "export_presets.cfg")
    for sec in cp.sections():
        if sec.endswith(".options"):
            continue
        if cp.get(sec, "name", fallback="").strip('"') == preset_name:
            return cp.get(sec + ".options", key).strip('"')
    raise SystemExit(f"preset {preset_name!r} not found")


def main():
    preset, flavor, build, sha, run = sys.argv[1:6]
    run_url = sys.argv[6] if len(sys.argv) > 6 else ""
    info = {
        "native_version": preset_option(preset, "version/name"),
        "native_build": int(build),
        "flavor": flavor,
        "source_sha": sha,
        "build_run": run,
        "build_run_url": run_url,
        "preset": preset,
    }
    out = ROOT / "scripts" / "generated" / "native_build_info.gd"
    out.parent.mkdir(exist_ok=True)
    body = ",\n".join(f'\t"{k}": {v!r}'.replace("'", '"') if isinstance(v, str) else f'\t"{k}": {v}' for k, v in info.items())
    out.write_text("extends RefCounted\n## GENERATED by tools/write_native_build_info.py at APK build time. Do not edit or commit.\n\n"
                   "const INFO := {\n" + body + ",\n}\n")
    print(out.read_text())


if __name__ == "__main__":
    main()
